### ISSUE TITLE
Allow tasks to depend on other tasks

### ISSUE THREAD

**Issue by davidahouse** [davidahouse/stampede-server#33]
For each section in a .stampede.yaml file (pull request, branch, release), there should be a way to trigger downstream tasks based on 3 possibilities:

- after a task has executed successfully
- after a task has failed
- when the build completes

To accomplish this, you can put `onSuccess` or `onFailure` lists of tasks under a single task, or `onComplete` at the same level as the `tasks:`.

Note that for now, you can't nest multiple `onSuccess` or `onFailure` blocks. The tasks in these blocks can have no further dependencies.

```
pullrequests:
  tasks:
    - id: pr-standards
      config:
        prMilestoneCheck: true
    - id: lint-nodejs
    - id: unit-tests-nodejs
      onSuccess:
         - id: sonar
         - id: whitehat
         - id: misc-reports
      onFailure:
         - id: task-notification
  onComplete:
     - id: success-notification
releases:
  published:
    tasks:
      - id: release-notes
      - id: npm-publish
```
