### ISSUE TITLE
Refactor notification handling

### ISSUE THREAD

**Issue by davidahouse** [davidahouse/stampede-server#537]
When the server implements the start or complete build notifications, it needs to check the build for a notification config. The notification config should tell the system if that build is setup to receive any notifications. If there is a match the notification handler should add a queue message for the channel provider so it can handle the notification asynchronously.

We will keep the current implementation of also sending the notification out to a notification queue as this is used by the test harness to validate the server executions.

Note: we may need to capture the notification section in the build config and pass along in our build details.

We should be able to handle any of the following sections in a `notification:` block in a build config:

```
branches:
  master:
    notifications:
      all:
        - channel-id: <id>
      start:
        - channel-id: <id>
      complete:
        - channel-id: <id>
      completeSuccess:
        - channel-id: <id>
      completeFailure:
        - channel-id: <id>
```

We need to support this `notifications:` block in any place in the stampede yaml file, along with any repository build configuration.

This issue doesn't cover the channel provider configuration. For testing we should add a basic channel provider that works similar to how the internal notification queue handler works so we can send channel messages to the test harness and it can validate that the correct notifications were sent.
