### ISSUE TITLE
Add .stampede.yaml wide config settings

### ISSUE THREAD

**Issue by davidahouse** [davidahouse/stampede-server#54]
We need to have `config:` at EVERY level of the .stampede.yaml file.

```
config:
pullrequests:
  config:
  tasks:
    - id: task_id
      config:
branches:
  config:
  branch:
     config:
     tasks:
        - id: task_id
          config:
releases:
   config:
   draft:
      config:
      tasks:
         - id: task_id
           config:
   published:
       config:
       tasks:
         - id: task_id
           config:
```
