### ISSUE TITLE
Repository based builds

### ISSUE THREAD

**Issue by davidahouse** [davidahouse/stampede-server#66]
Repository based builds are builds that can be triggered via Web UI, chatbot, API or a schedule. They are not triggered from GitHub events.

To define these jobs, we need to provide an admin screen that lets you upload the configuration for the jobs. These would be in a separate file for the repo. They should be in the following format:

```
jobs:
  uploadToAWS:
    tasks:
       - id: package-files
  sendEmail:
     tasks:
        - id: email-report
```

A job has a unique key, and should contain the following:

`tasks` to indicate what tasks the build should include. Exactly the same as other tasks nodes from PRs, branches, etc.

`title` to indicate what title should show up the UI in the list of runnable builds.

`schedule` to indicate if the build should auto-build on a schedule. Use the cron format of 5 tokens. For starters, however we will require the first two be set so we will default to a daily build at that specific minute & hour. We will create other issues to support the other parameters to only run builds on specific days of the week/month.
