### ISSUE TITLE
Refactor how builds are triggered from GitHub events

### ISSUE THREAD

**Issue by davidahouse** [davidahouse/stampede-server#90]
Currently we have a very small subset of events that can trigger builds. These cover the basic events from GitHub: pull request creation & update, branch pushes and release creation. There are cases where a more advanced triggering is desired, however. So the system will be enhanced to support both options.

This goes along with #66 which will introduce the top level `jobs:` functionality. Another top level key named `triggers:` will be added. This will contain any triggers that can be setup for the repository. 

Triggers are defined with the following:

- the event from GitHub (pull_request, push, etc)
- the action to match on
- another where section (need to design this out)
- either tasks or job to determine what tasks will be executed

Example:

```
triggers:
  - event: pull_request
     action: created
     tasks:
       - first-task
       - second-task
  - event: pull_request
    action: edit
    job:
       - edit-job
```

Note that a single event from GItHub can possibly trigger many builds. First it could match in one of the basic events, then one or more triggers.
